// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToPDF(arg1:Array<string>,arg2:string):Promise<Array<main.ConversionResult>>;

export function ConvertToWord(arg1:Array<string>,arg2:string):Promise<Array<main.ConversionResult>>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectOutputFolder():Promise<string>;

export function SelectPDFFiles():Promise<Array<string>>;
