// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertToPDF'](arg1, arg2);
}

export function ConvertToWord(arg1, arg2) {
  return window['go']['main']['App']['ConvertToWord'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function SelectPDFFiles() {
  return window['go']['main']['App']['SelectPDFFiles']();
}
